spring.application.name=job-tracker
server.port=${PORT:8081}
spring.data.mongodb.uri=${MONGODB_URI:mongodb://localhost:27017/jobtracker}
jsearch.api.key=${JSEARCH_API_KEY:}
gemini.api.key=${GEMINI_API_KEY:}

# Spring Mail (SMTP) Configuration
spring.mail.host=${SMTP_HOST:}
spring.mail.port=${SMTP_PORT:587}
spring.mail.username=${SMTP_USERNAME:}
spring.mail.password=${SMTP_PASSWORD:}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true