spring.application.name=job-tracker
server.port=8081
spring.data.mongodb.uri=mongodb://localhost:27017/jobtracker
gemini.api.key=AIzaSyBc-N2W5l0Ni-7P4odDh1Awhq0RLuEydG4
jsearch.api.key=a4af0dcc58mshbe71e2a14468cefp19af60jsn968a5cfb48a9